클럽 스키마 생성
jecraftx/nest-study-eventory pull request #6
Opened 2024-12-03 04:56 UTC by jecraftx

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
  클럽 스키마 생성

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-03 05:43 UTC, worjs requested changes

2024-12-03 05:43 UTC, worjs commented on prisma/schema.prisma
> +  members User[]  @relation("UserClubs")
Club과 User(참가자)는 ManyToMany Relation이기 때문에, 별도의 테이블을 만들어줘야 제대로 관계를 매핑할 수 있어요.

2024-12-03 05:43 UTC, worjs commented on prisma/schema.prisma
> +  members User[]  @relation("UserClubs")
Event와 User(참가자) 관계를 담은 테이블인 EventJoin 테이블을 참고!

2024-12-04 14:52 UTC, worjs requested changes
현재의 스키마는 다음과 같은 요구사항을 처리할 수 없어 보입니다.

1. 유저는 클럽에 가입 신청할 수 있다.
2. 클럽의 소유자는 가입 신청한 사람들 중 가입을 승인하거나, 거절할 수 있다.

즉, 신청하고 기다리는 사람들이라는 상태 역시 저장할 수 있어야 합니다!

2024-12-04 14:52 UTC, worjs commented on prisma/schema.prisma
> +  deletedAt   DateTime? @map("deleted_at")
지금 Event를 soft delete 해야하는 이유가 있나요?

2024-12-04 14:52 UTC, worjs commented on prisma/schema.prisma
> +  deletedAt   DateTime? @map("deleted_at")
클럽도 sotf delete 대상으로 하시는 이유가 있을까요?

2024-12-04 14:52 UTC, worjs commented on prisma/schema.prisma
> +  joinedAt  DateTime  @default(now()) @map("joined_at")
createdAt
updatedAt

위 필드는 메타데이터로, 데이터를 용이하게 관리하기 위해서 모든 테이블에 기본으로 추가하는 편입니다.
joinedAt 대신 createdAt, updatedAt을 넣어주면 좋을 것 같아요.

2024-12-05 09:57 UTC, jecraftx commented on prisma/schema.prisma
> +  joinedAt  DateTime  @default(now()) @map("joined_at")
알겠습니다. joinedAt 대신 createdAt과 updatedAt을 사용하는 방향으로 수정하겠습니다. 감사합니다!

2024-12-05 10:06 UTC, jecraftx commented on prisma/schema.prisma
> +  deletedAt   DateTime? @map("deleted_at")
삭제된 클럽을 복원하고 싶을 때 필요할 것 같아서 추가했는데.. 혹시 이 부분이 꼭 필요하지 않으면, 삭제해도 될까요?

2024-12-05 14:28 UTC, worjs commented on prisma/schema.prisma
> +  deletedAt   DateTime? @map("deleted_at")
아하 네네 복원을 해야하는 목적이라면 필요하지 않습니다 !

2024-12-07 02:19 UTC, worjs approved these changes

2024-12-07 02:34 UTC, merged